# Generated by Django 4.2.6 on 2024-04-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_usernotes_userreminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='notes_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='time_created',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
