# Generated by Django 4.2.6 on 2024-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_usernotes_notes_usernotes_notes_type_usernotes_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user note', max_length=300)),
                ('phone', models.CharField(max_length=300, null=True)),
                ('notes', models.CharField(max_length=300, null=True)),
                ('notes_type', models.CharField(max_length=300, null=True)),
                ('time_created', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'User Notes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserNotes',
        ),
    ]
