# Generated by Django 4.2.6 on 2024-05-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_usernote_delete_usernotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernote',
            options={'managed': False},
        ),
    ]
